Transform: AWS::Serverless-2016-10-31
Description: AWS SAM HttpApi with Cognito Authorizer

Parameters:
  AppName:
    Type: String
    Description: Application Name

Resources:
  ExpensesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: expenses
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  EmployeeTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: employees
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: role_name
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      GlobalSecondaryIndexes:
        - IndexName: employees_by_role_name
          KeySchema:
            - AttributeName: role_name
              KeyType: HASH
          Projection:
            ProjectionType: ALL

Outputs:
  ExpensesTableName:
    Value: 'expenses'
  EmployeesTableName:
    Value: 'employees'