Transform: AWS::Serverless-2016-10-31
Description: AWS SAM HttpApi with Cognito Authorizer

Parameters:
  AppName:
    Type: String
    Description: Application Name

Resources:
  ExpensesUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      UserPoolId: !Ref ExpensesUserPool
      GenerateSecret: false
      CallbackURLs:
        - "https://jwt.io"
      ClientName: !Sub ${AppName}-client
      SupportedIdentityProviders:
        - COGNITO
      AllowedOAuthFlows:
        - implicit
        - code
      AllowedOAuthScopes:
        - email
        - openid
        - profile
        - aws.cognito.signin.user.admin
        - phone
      AllowedOAuthFlowsUserPoolClient: true
      ExplicitAuthFlows:
        - ALLOW_ADMIN_USER_PASSWORD_AUTH
        - ALLOW_CUSTOM_AUTH
        - ALLOW_USER_SRP_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH

  ExpensesUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      AdminCreateUserConfig:
        AllowAdminCreateUserOnly: true
      UserPoolName: !Sub ${AppName}-users
      UsernameAttributes:
        - email
      Schema:
        - Name: email
          Mutable: true
          Required: true
        - Name: family_name
          Mutable: true
          Required: true
        - Name: given_name
          Mutable: true
          Required: true
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireLowercase: true
          RequireNumbers: true
          RequireSymbols: true
          RequireUppercase: true
          TemporaryPasswordValidityDays: 7

  ExpensesUserPoolDomain:
    Type: AWS::Cognito::UserPoolDomain
    Properties:
      Domain: !Sub ${AppName}-users
      UserPoolId: !Ref ExpensesUserPool

Outputs:
  ExpensesUserPool:
    Value: !Ref ExpensesUserPool
  ExpensesUserPoolClient:
    Value: !Ref ExpensesUserPoolClient