Transform: AWS::Serverless-2016-10-31
Description: AWS SAM HttpApi with Cognito Authorizer

Parameters:
  AppName:
    Type: String
    Description: Application Name
    Default: expenses

Globals:
  Function:
    Timeout: 300
    Architectures:
      - x86_64

Resources:

  ExpensesPythonLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: !Sub ${AppName}SharedPythonLayer
      Description: Python Layer for Expenses
      ContentUri: ./shared/
      CompatibleRuntimes:
        - python3.9
    Metadata:
      BuildMethod: python3.9

  ExpensesDb:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./db.yaml
      Parameters:
        AppName: !Ref AppName

  ExpensesStream:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./streams/streams.yaml
      Parameters:
        AppName: !Ref AppName
        EmployeesTableName: !GetAtt ExpensesDb.Outputs.EmployeesTableName
        ExpensesTableName: !GetAtt ExpensesDb.Outputs.ExpensesTableName
        ExpensesPythonLayer: !Ref ExpensesPythonLayer

  ExpensesIdentity:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./identity.yaml
      Parameters:
        AppName: !Ref AppName

  ExpensesApi:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./api/api.yaml
      Parameters:
        AppName: !Ref AppName
        EmployeesTableName: !GetAtt ExpensesDb.Outputs.EmployeesTableName
        ExpensesUserPool: !GetAtt ExpensesIdentity.Outputs.ExpensesUserPool
        ExpensesUserPoolClient: !GetAtt ExpensesIdentity.Outputs.ExpensesUserPoolClient
        ExpensesTableName: !GetAtt ExpensesDb.Outputs.ExpensesTableName
        ExpensesPythonLayer: !Ref ExpensesPythonLayer
        OnExpenseApprovedStreamArn: !GetAtt ExpensesStream.Outputs.OnExpenseApprovedStreamArn
        OnExpenseApprovedStreamName: !GetAtt ExpensesStream.Outputs.OnExpenseApprovedStreamName
        OnExpenseRejectedStreamArn: !GetAtt ExpensesStream.Outputs.OnExpenseRejectedStreamArn
        OnExpenseRejectedStreamName: !GetAtt ExpensesStream.Outputs.OnExpenseRejectedStreamName
        OnExpenseSubmittedStreamArn: !GetAtt ExpensesStream.Outputs.OnExpenseSubmittedStreamArn
        OnExpenseSubmittedStreamName: !GetAtt ExpensesStream.Outputs.OnExpenseSubmittedStreamName
