Transform: AWS::Serverless-2016-10-31
Description: AWS SAM Ultra Micro
Resources:
  MyFirstLambda:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: python3.9
      InlineCode: |
        def handler(event, context):
          return {
            'statusCode': 200,
            'body': 'Hello World'
          }
      Events:
        MyEvent:
          Type: HttpApi
          Properties:
            Path: /hello
            Method: get