Transform: AWS::Serverless-2016-10-31
Description: AWS SAM HttpApi

Globals:
  Function:
    Timeout: 300
    Architectures:
      - x86_64

Resources:
  HttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: api
      CorsConfiguration:
        AllowMethods:
          - GET
          - POST
          - PUT
          - DELETE
        AllowOrigins:
          - '*'
        AllowHeaders:
          - '*'

  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: main.handler
      Runtime: python3.9
      CodeUri: .
      Events:
        HelloWorld:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /hello
            Method: get