Transform: AWS::Serverless-2016-10-31
Description: AWS SAM HttpApi with Cognito Authorizer

Parameters:
  AppName:
    Type: String
    Description: Application Name

Resources:
  ExpensesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Expenses
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

Outputs:
  ExpensesTableArn:
    Value: !GetAtt ExpensesTable.Arn