Transform: AWS::Serverless-2016-10-31
Description: AWS SAM HttpApi with Cognito Authorizer

Parameters:
  AppName:
    Type: String
    Description: Application Name
    Default: expenses

Globals:
  Function:
    Timeout: 300
    Architectures:
      - x86_64

Resources:
  ExpensesDb:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./db.yaml
      Parameters:
        AppName: !Ref AppName

  ExpensesIdentity:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./identity.yaml
      Parameters:
        AppName: !Ref AppName

  ExpensesApi:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./api/api.yaml
      Parameters:
        AppName: !Ref AppName
        ExpensesUserPool: !GetAtt ExpensesIdentity.Outputs.ExpensesUserPool
        ExpensesUserPoolClient: !GetAtt ExpensesIdentity.Outputs.ExpensesUserPoolClient
        ExpensesTableArn: !GetAtt ExpensesDb.Outputs.ExpensesTableArn