Transform: AWS::Serverless-2016-10-31
Description: AWS SAM HttpApi with Function Authorization and Secrets Manager

Globals:
  Function:
    Timeout: 300
    Architectures:
      - x86_64

Resources:

  HttpApi:
    DependsOn:
      - MyTokenAuthFunction
    Type: AWS::Serverless::HttpApi
    Properties:
      Auth:       
        DefaultAuthorizer: MyLambdaTokenAuthorizer
        Authorizers:
          MyLambdaTokenAuthorizer:
            Identity:
              Headers:
                - 'X-API-Key'
            AuthorizerPayloadFormatVersion: '2.0'
            EnableSimpleResponses: true
            FunctionArn: !GetAtt MyTokenAuthFunction.Arn
            EnableFunctionDefaultPermissions: true
      StageName: api
      CorsConfiguration:
        AllowMethods:
          - GET
          - POST
          - PATCH
          - PUT
          - DELETE
        AllowOrigins:
          - '*'
        AllowHeaders:
          - '*'

  HttpApiKey:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: HttpApiKey
      Description: API Key for Http API
      GenerateSecretString:
        PasswordLength: 20

  MyTokenAuthFunction:
    DependsOn: 
      - HttpApiKey
    Type: AWS::Serverless::Function
    Properties:
      Handler: main.authorizer
      Runtime: python3.9
      CodeUri: .
      Environment:
        Variables:
          SECRET_KEY: HttpApiKey
      Policies: 
        - Version: '2012-10-17'
          Statement: 
            - Effect: Allow
              Action: secretsmanager:GetSecretValue
              Resource: !Sub arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:*

  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: main.handler
      Runtime: python3.9
      CodeUri: .
      Events:
        HelloWorld:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /hello
            Method: get
            PayloadFormatVersion: '2.0'