Transform: AWS::Serverless-2016-10-31
Description: AWS SAM HttpApi with Cognito Authorizer

Parameters:
  AppName: 
    Type: String
    Description: Application Name
  ExpensesUserPool:
    Type: String
    Description: Expenses User Pool
  ExpensesUserPoolClient:
    Type: String
    Description: Expenses User Pool Client
  ExpensesTableArn:
    Type: String
    Description: Expenses Table Name

Globals:
  Function:
    Timeout: 300
    Architectures:
      - x86_64

Resources:
  ApiPythonLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: ApiPythonLayer
      Description: Python dependencies for the API
      ContentUri: ./layers/
      CompatibleRuntimes:
        - python3.9
      RetentionPolicy: Retain

  HttpApiGw:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: api
      FailOnWarnings: true
      CorsConfiguration:
        AllowMethods:
          - GET
          - POST
          - PUT
          - DELETE
        AllowOrigins:
          - '*'
        AllowHeaders:
          - '*'
      Auth:
        Authorizers:
          MyOAuthAuthorizer:
            IdentitySource: $request.header.Authorization
            AuthorizationScopes:
              - email
            JwtConfiguration:
              issuer: !Sub 'https://cognito-idp.${AWS::Region}.amazonaws.com/${ExpensesUserPool}'
              audience: 
                - !Ref ExpensesUserPoolClient
              authType: JWT
        DefaultAuthorizer: MyOAuthAuthorizer

  ExpensesFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: main.handler
      Runtime: python3.9
      CodeUri: .
      Layers:
        - !Ref ApiPythonLayer
      Events:
        ExpensesGet:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApiGw
            Path: /expense
            Method: get
        ExpensesGetById:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApiGw
            Path: /expense/{id}
            Method: get
        ExpensesPost:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApiGw
            Path: /expense
            Method: post
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ExpensesTableArn
        