Transform: AWS::Serverless-2016-10-31
Description: AWS SAM HttpApi

Globals:
  Function:
    Timeout: 300
    Architectures:
      - x86_64

Resources:
  RestApiGw:
    Type: AWS::Serverless::Api
    Properties:
      StageName: api
      Cors: "'*'"
      Auth:
        DefaultAuthorizer: MyCognitoAuth
        Authorizers:
          MyCognitoAuth:
            UserPoolArn: !GetAtt HelloWorldUserPool.Arn

  HelloWorldUserPoolClient:
    DependsOn:
      - HelloWorldUserPool
      - HelloWorldUserPoolDomain
    Type: AWS::Cognito::UserPoolClient
    Properties:
      CallbackURLs:
        - "https://jwt.io"
      UserPoolId: !Ref HelloWorldUserPool
      ClientName: 'caparea-net-client'
      GenerateSecret: false
      SupportedIdentityProviders:
        - COGNITO
      AllowedOAuthFlows:
        - implicit
        - code
      AllowedOAuthScopes:
        - email
        - openid
        - profile
        - aws.cognito.signin.user.admin
        - phone
      AllowedOAuthFlowsUserPoolClient: true
      ExplicitAuthFlows:
        - ALLOW_ADMIN_USER_PASSWORD_AUTH
        - ALLOW_CUSTOM_AUTH
        - ALLOW_USER_SRP_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH

  HelloWorldUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      AdminCreateUserConfig:
        AllowAdminCreateUserOnly: true
      UserPoolName: !Sub ${AWS::StackName}-users
      UsernameAttributes:
        - email
      Schema:
        - Name: email
          Mutable: true
          Required: true
        - Name: family_name
          Mutable: true
          Required: true
        - Name: given_name
          Mutable: true
          Required: true
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireLowercase: true
          RequireNumbers: true
          RequireSymbols: true
          RequireUppercase: true
          TemporaryPasswordValidityDays: 7

  HelloWorldUserPoolDomain:
    Type: AWS::Cognito::UserPoolDomain
    Properties:
      Domain: !Sub ${AWS::StackName}-users
      UserPoolId: !Ref HelloWorldUserPool

  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: main.handler
      Runtime: python3.9
      CodeUri: .
      Events:
        HelloWorld:
          Type: Api
          Properties:
            RestApiId: !Ref RestApiGw
            Path: /hello
            Method: get